package com.example.aicodeanalyzer.repository;

import com.example.aicodeanalyzer.config.DatabaseConfig;
import com.example.aicodeanalyzer.config.DatabaseConnectionFactory;
import com.example.aicodeanalyzer.exception.DatabaseException;
import com.example.aicodeanalyzer.model.HandleAccount;
import com.example.aicodeanalyzer.model.Platform;
import com.example.aicodeanalyzer.model.Submission;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.concurrent.atomic.AtomicInteger;

public final class RepositoryTestSupport {
    private static final AtomicInteger DATABASE_SEQUENCE = new AtomicInteger();

    private RepositoryTestSupport() {
    }

    public static DatabaseConnectionFactory createFactoryWithSchema() {
        String databaseName = "repo_test_" + DATABASE_SEQUENCE.incrementAndGet();
        DatabaseConnectionFactory factory = new DatabaseConnectionFactory(new DatabaseConfig(
                "jdbc:h2:mem:" + databaseName
                        + ";MODE=MSSQLServer"
                        + ";DATABASE_TO_UPPER=false"
                        + ";CASE_INSENSITIVE_IDENTIFIERS=TRUE"
                        + ";DB_CLOSE_DELAY=-1",
                "sa",
                "",
                5
        ));
        createSchema(factory);
        return factory;
    }

    public static DatabaseConnectionFactory failingFactory() {
        return new DatabaseConnectionFactory(new DatabaseConfig("jdbc:h2:mem:failing", "sa", "", 5)) {
            @Override
            public Connection createConnection() {
                throw new DatabaseException("Forced connection failure for repository unit test.");
            }
        };
    }

    public static Platform seedPlatform(DatabaseConnectionFactory factory) {
        return new PlatformRepository(factory).save(new Platform(
                null,
                "CODEFORCES",
                "Codeforces",
                "https://codeforces.com",
                "https://codeforces.com/api",
                true,
                null,
                null
        ));
    }

    public static HandleAccount seedHandle(DatabaseConnectionFactory factory, long platformId, String handle) {
        return new HandleAccountRepository(factory).save(new HandleAccount(
                null,
                platformId,
                handle,
                handle,
                "demo",
                "PUBLIC",
                true,
                null,
                "Seeded handle",
                null,
                null
        ));
    }

    public static Submission submission(long handleId, String remoteId, LocalDateTime submittedAt) {
        return new Submission(
                null,
                handleId,
                remoteId,
                "1703A",
                "YES or YES?",
                "1703",
                "GNU C++17",
                "OK",
                submittedAt,
                46,
                102400L,
                800,
                "implementation,strings",
                "https://codeforces.com/contest/1703/submission/" + remoteId,
                null,
                null
        );
    }

    public static Timestamp sysUtcDateTime() {
        return Timestamp.valueOf(LocalDateTime.now(ZoneOffset.UTC));
    }

    private static void createSchema(DatabaseConnectionFactory factory) {
        try (Connection connection = factory.createConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA IF NOT EXISTS dbo");
            statement.execute("""
                    CREATE ALIAS IF NOT EXISTS SYSUTCDATETIME
                    FOR "com.example.aicodeanalyzer.repository.RepositoryTestSupport.sysUtcDateTime"
                    """);
            statement.execute("""
                    CREATE TABLE dbo.platforms (
                        platform_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code NVARCHAR(50) NOT NULL UNIQUE,
                        name NVARCHAR(100) NOT NULL,
                        base_url NVARCHAR(255),
                        api_url NVARCHAR(255),
                        is_active BOOLEAN DEFAULT TRUE NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                    )
                    """);
            statement.execute("""
                    CREATE TABLE dbo.programming_handles (
                        handle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        platform_id BIGINT NOT NULL,
                        handle NVARCHAR(100) NOT NULL,
                        display_name NVARCHAR(150),
                        group_name NVARCHAR(100),
                        rating INT,
                        rank_name NVARCHAR(50),
                        general_evaluation CLOB,
                        consent_status VARCHAR(30) DEFAULT 'UNKNOWN' NOT NULL,
                        is_active BOOLEAN DEFAULT TRUE NOT NULL,
                        last_crawled_at TIMESTAMP,
                        notes NVARCHAR(500),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        CONSTRAINT uq_programming_handles_platform_handle UNIQUE (platform_id, handle),
                        CONSTRAINT fk_programming_handles_platform
                            FOREIGN KEY (platform_id) REFERENCES dbo.platforms(platform_id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE dbo.submissions (
                        submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        platform_id BIGINT NOT NULL,
                        handle_id BIGINT NOT NULL,
                        platform_submission_id NVARCHAR(100) NOT NULL,
                        problem_code NVARCHAR(100),
                        problem_name NVARCHAR(255),
                        contest_id NVARCHAR(100),
                        language NVARCHAR(100),
                        verdict VARCHAR(50),
                        submitted_at TIMESTAMP,
                        execution_time_ms INT,
                        memory_bytes BIGINT,
                        problem_rating INT,
                        problem_tags NVARCHAR(1000),
                        source_url NVARCHAR(500),
                        source_crawl_status VARCHAR(30) DEFAULT 'PENDING' NOT NULL,
                        source_crawled_at TIMESTAMP,
                        source_crawl_error NVARCHAR(1000),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        CONSTRAINT uq_submissions_platform_remote UNIQUE (platform_id, platform_submission_id),
                        CONSTRAINT fk_submissions_platform
                            FOREIGN KEY (platform_id) REFERENCES dbo.platforms(platform_id),
                        CONSTRAINT fk_submissions_handle
                            FOREIGN KEY (handle_id) REFERENCES dbo.programming_handles(handle_id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE dbo.source_codes (
                        source_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        submission_id BIGINT NOT NULL,
                        code_content CLOB,
                        code_hash NVARCHAR(128),
                        line_count INT,
                        char_count INT,
                        fetched_at TIMESTAMP,
                        storage_type VARCHAR(50) DEFAULT 'DATABASE' NOT NULL,
                        is_encrypted BOOLEAN DEFAULT FALSE NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        CONSTRAINT uq_source_codes_submission UNIQUE (submission_id),
                        CONSTRAINT fk_source_codes_submission
                            FOREIGN KEY (submission_id) REFERENCES dbo.submissions(submission_id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE dbo.ai_analysis_results (
                        analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        submission_id BIGINT NOT NULL,
                        analyzer_type VARCHAR(50),
                        analyzer_version VARCHAR(50),
                        model_name NVARCHAR(100),
                        data_structures NVARCHAR(1000),
                        algorithms NVARCHAR(1000),
                        complexity_estimate NVARCHAR(1000),
                        code_quality_score DECIMAL(5,2),
                        ai_risk_score DECIMAL(5,2),
                        ai_risk_level VARCHAR(30),
                        summary NVARCHAR(4000),
                        raw_response CLOB,
                        prompt_hash NVARCHAR(128),
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        CONSTRAINT fk_ai_analysis_results_submission
                            FOREIGN KEY (submission_id) REFERENCES dbo.submissions(submission_id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE dbo.user_skill_scores (
                        score_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        handle_id BIGINT NOT NULL,
                        period_start DATE NOT NULL,
                        period_end DATE NOT NULL,
                        data_structure_score DECIMAL(5,2) DEFAULT 0 NOT NULL,
                        algorithm_score DECIMAL(5,2) DEFAULT 0 NOT NULL,
                        problem_solving_score DECIMAL(5,2) DEFAULT 0 NOT NULL,
                        code_quality_score DECIMAL(5,2) DEFAULT 0 NOT NULL,
                        practice_consistency_score DECIMAL(5,2) DEFAULT 0 NOT NULL,
                        ai_usage_risk_score DECIMAL(5,2) DEFAULT 0 NOT NULL,
                        overall_score DECIMAL(5,2) DEFAULT 0 NOT NULL,
                        summary NVARCHAR(4000),
                        generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        CONSTRAINT uq_user_skill_scores_handle_period UNIQUE (handle_id, period_start, period_end),
                        CONSTRAINT fk_user_skill_scores_handle
                            FOREIGN KEY (handle_id) REFERENCES dbo.programming_handles(handle_id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE dbo.crawl_logs (
                        crawl_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        job_type VARCHAR(50) NOT NULL,
                        status VARCHAR(30) NOT NULL,
                        started_at TIMESTAMP,
                        finished_at TIMESTAMP,
                        total_handles INT DEFAULT 0 NOT NULL,
                        total_new_submissions INT DEFAULT 0 NOT NULL,
                        total_errors INT DEFAULT 0 NOT NULL,
                        message CLOB,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                    )
                    """);
        } catch (SQLException ex) {
            throw new DatabaseException("Cannot create H2 repository test schema: " + ex.getMessage(), ex);
        }
    }
}
